services:

  db:
    image: postgres:13.0-alpine
    container_name: maranomadstore_local_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=marastore
      - POSTGRES_USER=marastore
      - POSTGRES_PASSWORD=marastore
  rabbit:
    hostname: localhost
    image: rabbitmq:3.6.9
    container_name: maranomadstore_local_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/
      # - CELERY_BROKER_URL=amqp://user:password@rabbit:5672
      - CELERY_BROKER_URLamqp://guest:**@127.0.0.1:5672//
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
  redis:
    image: redis:6
    container_name: maranomadstore_local_redis

  web: &web
    build: .
    image: maranomadstore_local_web
    container_name: maranomadstore_local_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/maranomadstore/
    ports:
      - 8000:8000
    # env_file:
    #   - ./.env.dev
    # environment:
    #   - name=value
    links:
      - db
      - rabbit
    depends_on:
      - db
      - redis
      - rabbit
    restart: "on-failure"

  celeryworker:
    <<: *web
    image: maranomadstore_local_celeryworker
    container_name: maranomadstore_local_celeryworker
    depends_on:
      - redis
      - db
    ports: []
    command: celery -A maranomadstore worker -l info

  flower:
    <<: *web
    image: maranomadstore_local_flower
    container_name: maranomadstore_local_flower
    ports:
      - "5555:5555"
    command: celery -A maranomadstore flower

# persist data beyond life of container
volumes:
  postgres_data:
