# Generated by Django 4.1.3 on 2022-12-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_braintree_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created",),
                "verbose_name": "order",
                "verbose_name_plural": "orders",
            },
        ),
    ]
